### ISSUE TITLE
Multicall

### ISSUE THREAD

**Issue by chnejohnson** [chnejohnson/splitter#6]
- https://ethereum.stackexchange.com/questions/99327/single-call-vs-multicall
- https://medium.com/ethworks/introducing-usedapp-developer-tools-d52fe77e8230

**Comment by johnson86tw** [comment]
Done.
https://github.com/chnejohnson/splitter/blob/712cb4b4e36b419fbfe2d9b11bdc3d246c9a2330/frontend/src/composables/splitter.ts#L102
